#!/bin/bash

mkdir -p src
mkdir -p dest
mkdir -p src/folder1
mkdir -p src/folder2
mkdir -p src/folder1/sub1
mkdir -p src/folder1/sub1/subsub1
mkdir -p src/folder2/sub2
mkdir -p src/folder2/sub3
mkdir -p src/folder2/sub4
mkdir -p src/folder2/sub3/subzero

mkdir -p dest/folder2
mkdir -p dest/folder3
mkdir -p dest/folder2/sub2
mkdir -p dest/folder3/sub1
mkdir -p dest/folder3/sub2
mkdir -p dest/folder3/sub1/subzero

echo "starszy plik" > dest/zmodyfikowany
head -c 500M /dev/urandom > src/sample500M.txt
echo "nowszy plik" > src/zmodyfikowany
echo "plik do usuniecia" > dest/dousuniecia
head -c 100M /dev/urandom > src/folder1/sample100M.txt
head -c 10M /dev/urandom > src/folder2/sub3/sample10M.txt
head -c 50M /dev/urandom > src/folder1/sub1/subsub1/sample50M.txt
head -c 5M /dev/urandom > src/folder1/sub1/sample5M.txt
echo "starszy plik" > dest/folder2/zmodyfikowany
head -c 50M /dev/urandom > src/folder2/sub2/sample50M.txt
echo "nowszy plik" > src/folder2/zmodyfikowany
echo "plik do usuniecia" > dest/folder2/dousuniecia
head -c 5M /dev/urandom > dest/folder3/sub1/subzero/sample5M.txt
head -c 5M /dev/urandom > src/folder2/sub2/sample5M.txt
